learning_log/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]


learning_logs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that show all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Page for deleting entry
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    # Page for deleting topic
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
]


users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/userlogin.html'), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField(default='Pls enter data')
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}



learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/end_topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/front_topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)  # Save topic in a variable.
            new_topic.owner = request.user  # Set topics owner attribute to current user.
            new_topic.save()  # Save the changes to the database.
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/add_new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/add_new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/entry_update.html', context)

@login_required
def delete_entry(request, entry_id):
    """Delete an entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method == 'POST':
        entry.delete()
        return redirect('learning_logs:topic', topic_id=topic.id)

    # Render a confirmation page for GET request
    context = {'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/delete_entry.html', context)


@login_required
def delete_topic(request, topic_id):
    """Delete a topic."""
    topic = Topic.objects.get(id=topic_id) # Fetch the topic to be deleted
    if topic.owner != request.user:
        raise Http404

    if request.method == 'POST':
        topic.delete()
        return redirect('learning_logs:topics')

    # Render a confirmation page for GET request
    context = {'topic': topic}
    return render(request, 'learning_logs/delete_topic.html', context)

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/user_registration.html', context)

learning_logs/templates/learning_logs/add_new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h2>Add a new entry:</h2>
{% endblock header %}

{% block content %}

<h3>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</h3>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}

    {% bootstrap_form form%}

    {% buttons%}
    <button name='submit' class="btn btn-success">Add Entry</button>
    {% endbuttons%}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/add_new_topic.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-success">Add Topic</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log Application</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body style="background-color: skyblue">
    <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top" style="background-color: whitesmoke">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar"></button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                    Home
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                    <li><a href="{% url 'users:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>

    </div> <!-- /container -->

</body>

</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Delete Entry</h2>
  <p>Are you sure you want to delete this entry?</p>
  <p>{{ entry.text|linebreaks }}</p>

  <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Delete Topic</h2>
  <p>Are you sure you want to delete the topic "{{ topic }}" and all its entries?</p>

  <form action="{% url 'learning_logs:delete_topic' topic.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'learning_logs:topics' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/end_topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>Topics</h1>
{% endblock header%}

{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>
        No topics have been added yet.
    </li>
    {% endfor %}
</ul>

<h2 class="btn btn-success">
    <a style="color: white" href="{% url 'learning_logs:new_topic' %}">Add a New Topic</a>
</h2>

{% endblock content %}

learning_logs/templates/learning_logs/entry_update.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h2>Edit entry:</h2>
{% endblock header %}

{% block content %}

<h3>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
</h3>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}

    {% bootstrap_form form%}

    {% buttons%}
    <button name='submit' class="btn btn-success">Save Changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/front_topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

<p class="btn btn-success">
    <a class="btn btn-primary" href="{% url 'learning_logs:new_entry' topic.id %}">Add New Entry</a>
     <a class="btn btn-danger" href="{% url 'learning_logs:delete_topic' topic.id %}" style="margin-right: 30px">Delete topic</a>
        <a class="btn btn-primary" href="{% url 'learning_logs:topics' %}">Back</a>
</p>

<br></br>
<ul>
    {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                {{ entry.date_added | date:'M d, Y H:i' }}
                <small>
                    <a class="btn btn-success" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a>
                     <a class="btn btn-danger" href="{% url 'learning_logs:delete_entry' entry.id %}">Delete entry</a>
    </small>
            </h2>
        </div>
        <div class="panel-body">
            {{ entry.text | linebreaks }}
        </div>
    </div> <!-- panel -->
    {% empty %}
    There are no entries for this topic yet.
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class='jumbotron'>
    <h1>Reserve a Space for Your Learning Logs</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log.
</h2>
 <h2>
   A Learning Log is your personal space to reflect on your thoughts, questions, and progress as you explore new knowledge and skills. Learning is a journey, and your log becomes a valuable record of how you grow and adapt along the way. It’s not just about what you learn—it’s about how you learn, what challenges you overcome, and the insights you discover.
</h2>
<h2>
    Begin your journey now - your Learning Log is waiting!!
</h2>
{% endblock content %}

users/templates/users/user_registration.html
{% extends "learning_logs/base.html" %}
{% block content %}
<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="btn btn-success">Register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}

users/templates/users/userlogin.html
{% extends "learning_logs/base.html" %}
{% block content %}
 {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>  {% endif %}
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="btn btn-success">Log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>     
   {% endblock content %}